### ISSUE TITLE
Unzip: not found

### ISSUE THREAD

**Issue by charlestbell** [icflorescu/expose-wsl#3]
Hi @icflorescu,

I love the idea of this project. Currently trying to use it with expo.

Here is what the command line is spitting out:
![Screenshot 2023-04-18 113344](https://user-images.githubusercontent.com/54514092/232828778-d1c5d851-ec54-41fe-b7b1-290ece61f3f5.png)

Windows 11
WSL2 with Ubuntu 22.04.1 LTS

Any ideas?

**Comment by ghosty2004** [comment]
try to execute `apt-get install unzip`

**Comment by charlestbell** [comment]
Thanks @Ghosty2004 That solved the first issue.

**Comment by ghosty2004** [comment]
> Thanks @Ghosty2004 That solved the first issue.

The second one is also present for me. Can you close this issue and create a new one with the new error?

**Comment by icflorescu** [comment]
@charlestbell - running expo on Windows/WSL was the exact reason I started this little project in the first place :-)

Thanks for coming up with a response so quickly, @Ghosty2004. I had no idea that the default Ubuntu 22 is coming without `unzip`.

What is the second issue?

**Comment by charlestbell** [comment]
@icflorescu The second issue isn't with this package (I don't think)
 I'm using this package for expo development, and it doesn't work over lan, only if I use --tunnel. I didn't mention it because it was expo-specific.

**Comment by icflorescu** [comment]
The latest `expose-wsl` version doesn't rely on `unzip`, so this shouldn't be a problem anymore 🎉
